on:
  push:
    branches: [master]

name: 🚀 Deploy orRank
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 🐛 Validate composer.json and composer.lock
        run: composer validate --strict

      - name: 🔨 Install Composer dependencies
        run: composer install

      - name: 🔨 Install NPM dependencies Setup Laravel move directory
        run: npm install && npm run dev

      #- name: 🔨 Setup Laravel Env
      #  run: cp .env.example .env

      - name: 🚀 Deploy 📂 Sync files 🎉
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.orrank.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/Laravel/
          exclude: vendor/**
            - vendor/**/*
            - node_modules/**
            - node_modules/**/*
            - .github/**/*
            - .git/**/*
            - public/**/*
            - bootstrap/**/*
