on:
  push:
    branches: [ master ]

name: 🚀 Deploy orRank
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 🐛 Validate composer.json and composer.lock
      run: composer validate --strict

    - name: 📂 Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: 🔨 Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: 🔨 Install NPM dependencies Setup Laravel move directory
      run: npm install && npm run dev
      
   # - name: 🔨 Setup Laravel directory structure
   #   run: mv 
        
    - name: 🚀 Deploy 📂 Sync files 🎉
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.orrank.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/Laravel/
